apiVersion: v1
kind: Namespace
metadata:
  name: team6
  labels:
    name: team6
    project: cs3891-pa3
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: spark-service-account
  namespace: team6
---
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  namespace: team6
  name: spark-role
rules:
- apiGroups: [""]
  resources: ["pods"]
  verbs: ["get", "watch", "list", "create", "delete"]
- apiGroups: [""]
  resources: ["services"]
  verbs: ["get", "create", "delete"]
- apiGroups: [""]
  resources: ["configmaps"]
  verbs: ["get", "create", "delete"]
---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: spark-role-binding
  namespace: team6
subjects:
- kind: ServiceAccount
  name: spark-service-account
  namespace: team6
roleRef:
  kind: Role
  name: spark-role
  apiGroup: rbac.authorization.k8s.io