database:
  host: "mysql"
  port: 3306
  user: "energy_user"
  password: "energy_pass"
  database: "energy_db"
  num_shards: 5

connection:
  pool_size: 10
  max_overflow: 20
  pool_timeout: 30
  pool_recycle: 3600